### ISSUE TITLE
Typo importing __spreadArrays from tslib

### ISSUE THREAD

**Issue by bestexec** [FirebaseExtended/rxfire#31] opened 2021-09-06 12:21 UTC
in rxfire/firestore/index.esm.js __spreadArray is imported instead of __spreadArrays

**Comment by evdama** [comment] 2022-02-21 21:19
@davideast Hi David, could you maybe do this quick fix?

**Comment by DavidWeiss2** [comment] 2022-03-21 09:30
@davideast Please fix it <3

**Comment by evdama** [comment] 2022-03-21 09:34
If @jamesdaniels and @davideast is too busy, what about adding more maintainers so reaction times for issues und PRs are reasonable?

**Comment by DavidWeiss2** [comment] 2022-03-23 23:52
@evdama Just because I was curious, I looked into tslib new versions, in the new version there is a "array" and "arrays" options. The problem is that the version used by this package does not work with the new versions of tslib based on my assumption.

**Comment by evdama** [comment] 2022-03-24 07:47
@DavidWeiss2 I see, this will be another issue then I guess because current tslib is 2.3.1 whereas 2.1.0 is used here atm https://github.com/FirebaseExtended/rxfire/blob/95ffa992e64fe97187ed11d9f775d97e8c3f9567/package.json#L80

**Comment by DavidWeiss2** [comment] 2022-03-28 11:49
this is sad:
https://github.com/FirebaseExtended/rxfire/branches/active

no active work on this one.

**Comment by DavidWeiss2** [comment] 2022-07-05 11:58
Nice. Thanks for shring.

**Comment by YannicEl** [comment] 2022-07-05 12:18
> For anyone finding this, i could get around this by overriding the dependency in package.json
> 
> ```
> "pnpm": {
>   "overrides": {
>     "tslib": "^2.3.1"
>   }
> }
> ```

Thank you for the fix. I think your solution overdrives tslib in the entire dependency gaph meaning that every package depending on tslib will use your specified version. This is according to the pnpm [docs](https://pnpm.io/package_json#pnpmoverrides).
You could do something like this.

```
"pnpm": {
  "overrides": {
    "rxfire>tslib": "2"
  }
}
```

This will only override tslib in the rxfire package.

**Comment by davideast** [comment] 2023-07-11 19:38
First of all, we apologize for letting this issue sit for far too long. We believe it was addressed in the past with a dependency update of `tslib`. I've pushed #74 to move tslib to the current latest as well. This library did sit on the back burner for awhile with other priorities taking center. However, it sat for too long and I'll be ensuring that it doesn't get into this state again.

If this issue persists *please* open a new issue and I'll address it.

**Closed by davideast** 2023-07-11 19:38 UTC
